const express = require("express")
const router = express.Router()
const auth = require("../middleware/authMiddleware")
const createOrder = require("../controllers/order/createOrder")
const getOrders = require("../controllers/order/getOrders")
const trackOrder = require("../controllers/order/trackOrder")
const createPayment = require("../controllers/order/createPayment")
const verifyPayment = require("../controllers/order/verifyPayment")
const getTracking = require("../controllers/tracking/getTracking")
const getQuote = require("../controllers/tracking/getQuote")
const { cancelOrder, cancelItem } = require("../controllers/order/cancelOrder")
const reorder = require("../controllers/order/reorder")

router.post("/create-payment", auth, createPayment)
router.post("/verify-payment", auth, verifyPayment)
router.post("/", auth, createOrder)
router.get("/", auth, getOrders)
router.get("/quote", auth, getQuote)
router.get("/:id/tracking", auth, getTracking)
router.get("/:id", auth, trackOrder)

router.post("/:id/cancel", auth, cancelOrder)
router.post("/:id/items/:itemId/cancel", auth, cancelItem)
router.post("/:id/reorder", auth, reorder)

module.exports = router